(define (problem Do-minecraft-house)
   (:domain minecraft-house)
   (:objects c5 c4 c3 c2 c1 d5 d4 d3 d2 d1 p5 p4 p3 p2 p1 z5 z4 z3 z2 z1 k5 k4 k3 k2
             k1)
   (:init (wood c5)
          (wood c4)
          (wood c3)
          (wood c2)
          (wood c1)
          (stone d5)
          (stone d4)
          (stone d3)
          (stone d2)
          (stone d1)
          (bricks p5)
          (bricks p4)
          (bricks p3)
          (bricks p2)
          (bricks p1)
          (flowers z5)
          (flowers z4)
          (flowers z3)
          (flowers z2)
          (flowers z1)
          (sand k5)
          (sand k4)
          (sand k3)
          (sand k2)
          (sand k1)          )
   (:goal (and (have-wood)
               (have-stone)
               (have-bricks)
               (have-flowers)
               (have-sand)
               (have-materials)
               (have-house)
               (have-tools)
               (have-craftting-table)
               )))